# Generated by Django 3.2.18 on 2023-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, '男'), (1, '女')], null=True, verbose_name='性别'),
        ),
    ]
